Morphological Transformation
===

## Erosion

Basically, it erodes away the boundaries of foreground object. We deal with image having a white foreground here. What it does is have a kernel slide through an image (similar to 2D convolution). A pixel in the original image will be considered 1 only if all the pixels under the kernel is 1, it is eroded otherwise (converted to 0).

Let's try to improve the `figures/bookpage.jpg` thresholding in **Image Thresholding** session.

In [1]:
import cv2
import numpy as np

Let's load the `figures/bookpage.jpg` image as our sample data.

In [2]:
bookread = cv2.imread('figures/bookpage.jpg')

Convert the image to grayscale.

In [3]:
grayscaled = cv2.cvtColor(bookread, cv2.COLOR_BGR2GRAY)

Perform adaptive threshold to get the "clearer" version of the `bookread` image.

In [4]:
gauss = cv2.adaptiveThreshold(grayscaled, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 115, 1)

Since erosion deals with binary images only, with the foreground being white; background being black, we have to get the inverse mask of our image.

In [5]:
gauss_inv = cv2.bitwise_not(gauss)

For now, let's take a look at our resulting images.

In [6]:
cv2.namedWindow('bookread', cv2.WINDOW_NORMAL)
cv2.namedWindow('bookread_grayscaled', cv2.WINDOW_NORMAL)
cv2.namedWindow('bookread_gauss', cv2.WINDOW_NORMAL)
cv2.namedWindow('bookread_gauss_inv', cv2.WINDOW_NORMAL)
cv2.imshow('bookread', bookread)
cv2.imshow('bookread_grayscaled', grayscaled)
cv2.imshow('bookread_gauss', gauss)
cv2.imshow('bookread_gauss_inv', gauss_inv)
cv2.waitKey(0)
cv2.destroyAllWindows()

Now that we've seen what `gauss_inv` looks like, we have visually confirmed that it suits our requirement for erosion.

As mentioned above, the idea of erosion is to slide a kernel through an image. So, let's create a kernel as our first step.

In [7]:
kernel = np.ones((2, 2), np.uint8)
print(kernel)

[[1 1]
 [1 1]]


Let's get a sample region of interest, then display its values.

In [8]:
roi = gauss_inv[0:4, 0:4]
print(roi)

[[  0   0   0 255]
 [255 255   0   0]
 [255 255   0   0]
 [255 255   0   0]]


Let's perform an erosion on our selected ROI.

In [9]:
erosion = cv2.erode(roi, kernel, iterations=1)
print(erosion)

[[  0   0   0   0]
 [  0   0   0   0]
 [255 255   0   0]
 [255 255   0   0]]


Seeing how erosion operates, it will "clean" the boundaries of a foreground object by getting its minimum values. Let's perform erosion on the entire inverted gaussian-threshold image.

In [10]:
erosion = cv2.erode(gauss_inv, kernel, iterations=1)

Let's convert our image back to having a black foreground and white background by using `cv2.bitwise_not()`.

In [11]:
erosion = cv2.bitwise_not(erosion)

Let's display the original image, the image without erosion, and the one with erosion.

In [12]:
cv2.imshow('original_image', bookread)
cv2.imshow('gaussian', gauss)
cv2.imshow('eroded', erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Dilation

This is basically the opposite of erosion. Here, a pixel element is '1' if atleast one pixel under the kernel is '1'. In other words, it's getting maximum values of a foreground object instead of getting the minimum values.

In [13]:
dilation = cv2.dilate(gauss_inv, kernel, iterations=1)

Let's convert our image back to having a black foreground and white background by using `cv2.bitwise_not()`.

In [14]:
dilation = cv2.bitwise_not(dilation)

Let's display the original image, the image without erosion, the one with erosion, and the dilated one.

In [15]:
cv2.imshow('original_image', bookread)
cv2.imshow('gaussian', gauss)
cv2.imshow('eroded', erosion)
cv2.imshow('dilated', dilation)
cv2.imshow
cv2.waitKey(0)
cv2.destroyAllWindows()

## Opening

This may seem to be an erosion followed by dilation. This is useful for removing noise, and we do so by using `cv2.morphologyEx()`.

In [16]:
opening = cv2.morphologyEx(gauss_inv, cv2.MORPH_OPEN, kernel)

Let's convert our image back to having a black foreground and white background by using `cv2.bitwise_not()`.

In [17]:
opening = cv2.bitwise_not(opening)

Let's display the original image, the image without erosion, the one with erosion, the dilated one, and the opening one.

In [18]:
cv2.imshow('original_image', bookread)
cv2.imshow('gaussian', gauss)
cv2.imshow('eroded', erosion)
cv2.imshow('dilated', dilation)
cv2.imshow('opening', opening)
cv2.imshow
cv2.waitKey(0)
cv2.destroyAllWindows()

## Closing

This may seem to be an dilation followed by erosion. It is useful for closing small holes within the foreground objects. We also use `cv2.morphologyEx()`.

In [19]:
closing = cv2.morphologyEx(gauss_inv, cv2.MORPH_CLOSE, kernel)

Let's convert our image back to having a black foreground and white background by using `cv2.bitwise_not()`.

In [20]:
closing = cv2.bitwise_not(closing)

Let's display the original image, the image without erosion, the one with erosion, the dilated one, the opening one, and the closing one.

In [21]:
cv2.imshow('original_image', bookread)
cv2.imshow('gaussian', gauss)
cv2.imshow('eroded', erosion)
cv2.imshow('dilated', dilation)
cv2.imshow('opening', opening)
cv2.imshow('closing', closing)
cv2.imshow
cv2.waitKey(0)
cv2.destroyAllWindows()

## Morphological Gradient

The difference between dilation and erosion of an image.

In [22]:
gradient = cv2.morphologyEx(gauss_inv, cv2.MORPH_GRADIENT, kernel)

Let's convert our image back to having a black foreground and white background by using `cv2.bitwise_not()`.

In [23]:
gradient = cv2.bitwise_not(gradient)

Let's display the original image, the image without erosion, the one with erosion, the dilated one, the opening one, the closing one, and the morphological gradient.

In [24]:
cv2.imshow('original_image', bookread)
cv2.imshow('gaussian', gauss)
cv2.imshow('eroded', erosion)
cv2.imshow('dilated', dilation)
cv2.imshow('opening', opening)
cv2.imshow('closing', closing)
cv2.imshow('morphological_gradient', gradient)
cv2.imshow
cv2.waitKey(0)
cv2.destroyAllWindows()

## Exercise

Isolate an object based on a color from a video (same with **4-changing-colorspace**), and use morphological transformations to improve the isolated object.

cap = cv2.VideoCapture(0)

while True:
    
    # take each frame
    _, frame = cap.read()
    
    # convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    # define the range of blue color in HSV
    lower_blue = np.array([110, 50, 50])
    upper_blue = np.array([130, 255, 255])
    
    # threshold the HSV image to get only blue colors
    mask = cv2.inRange(hsv, lower_blue, upper_blue)
    
    # bitwise-and the mask and the original image
    res = cv2.bitwise_and(frame, frame, mask=mask)
    
    kernel = np.ones((5, 5), np.uint8)
    erosion = cv2.erode(mask, kernel, iterations=1)
    dilation = cv2.dilate(mask, kernel, iterations=1)
    opening = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    closing = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    
    cv2.imshow('frame', frame)
    cv2.imshow('mask', mask)
    cv2.imshow('res', res)
    cv2.imshow('eroded_mask', erosion)
    cv2.imshow('dilated_mask', dilation)
    cv2.imshow('opening', opening)
    cv2.imshow('closing', closing)
    
    k = cv2.waitKey(5)
    
    if k == 27:
        break
        
cv2.destroyAllWindows()